### ISSUE TITLE
Order of attacker name and team is reversed for damage and kill events

### ISSUE THREAD

**Issue by RaidMax** [Joelrau/S1x-IW6x-g_log-script#1]
https://github.com/Joelrau/S1x-IW6x-g_log-script/blob/main/scripts/logging/log.lua#L83-L84

https://github.com/Joelrau/S1x-IW6x-g_log-script/blob/main/scripts/logging/log.lua#L115-L116

both occurrences print name then team for attacker.

Per most cods this should be 
team, then name

examples
iw4 - https://github.com/shit-ware/IW4/blob/master/maps/mp/gametypes/_damage.gsc#L1462
iw3 - https://github.com/volkv/CoD4-Default-GSC-Scripts/blob/master/maps/mp/gametypes/_globallogic.gsc#L4657
t5 - https://github.com/itacentury/CenturyPackageBO1/blob/master/maps/mp/gametypes/_globallogic_player.gsc#L1112

**Comment by Joelrau** [comment]
Oops. Good catch.
